FROM python:3.11

WORKDIR /app

COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

COPY backend/models/ /app/models/

EXPOSE 8000

CMD ["python", "main.py"]
